name: REUSE

on:
  push:
    branches:
      - v3
  pull_request:
    branches:
      - v3

jobs:
  compliance-check:
    name: Compliance Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Execute REUSE Compliance Check
      uses: fsfe/reuse-action@v2
