name: REUSE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compliance-check:
    name: Compliance Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Execute REUSE Compliance Check
      uses: fsfe/reuse-action@v1.1
