name: REUSE

on:
  push:
    branches:
      - v2
      - main
      - next
  pull_request:
    branches:
      - v2
      - main
      - next

jobs:
  compliance-check:
    name: Compliance Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Execute REUSE Compliance Check
      uses: fsfe/reuse-action@v1.1
