name: REUSE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# No permissions are required for this workflow
permissions: {}

jobs:
  compliance-check:
    name: Compliance Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Execute REUSE Compliance Check
      uses: fsfe/reuse-action@v5
