name: Security Audit

on:
  schedule:
    - cron: "36 4 * * *" # Run once a day
  workflow_dispatch:

# No permissions are required for this workflow
permissions: {}

jobs:
  security-scan:
    name: Security Audit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["main", "v3"] # List of branches to run the security audit on

    steps:
      - name: Checkout '${{ matrix.branch }}' branch
        uses: actions/checkout@v5
        with:
          ref: ${{ matrix.branch }}

      - name: Use audit-ci
        run: npx audit-ci@^7 --config ./audit-ci.jsonc
