name: Security Audit

on:
  schedule:
    - cron: "36 4 * * *" # Run once a day

jobs:
  security-scan:
    name: Security Audit
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        branch: ["v2"] # List of branches to run the security audit uppon

    steps:
      - name: Checkout the default branch (security configuration)
        uses: actions/checkout@v3
        with:
          path: default

      - name: Checkout '${{ matrix.branch }}' branch
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
          path: ${{ matrix.branch }}

      - name: Install '${{ matrix.branch }}' dependencies
        run: |
          cd ${{ matrix.branch }}
          npm ci

      - name: Security check for '${{ matrix.branch }}' branch
        run: |
          cd ${{ matrix.branch }}
          npx audit-ci@^6 --config ../default/audit-ci.jsonc
